### ISSUE TITLE
HTML Paste is broken

### ISSUE THREAD

**Issue by dselman** [accordproject/markdown-editor#198]
**Describe the bug**
Copying HTML from another webpage and pasting it into the markdown editor should work.

**To Reproduce**
1. Go to any webpage
2. Select some text and copy to the clipboard
3. Open the markdown editor and press paste
4. Nothing is inserted into the editor

**Expected behavior**
COPY/PASTE of html text should work.

**Comment by irmerk** [comment]
@DianaLease is this closed with #211 and [`markdown-transform` #138](https://github.com/accordproject/markdown-transform/pull/138)?

**Comment by jeromesimeon** [comment]
@irmerk I wouldn't mind keeping this open just for a little longer, notably because I do not believe we have very clear requirements for this yet. I think with #211 and #138 we have moved from the behaviour description in the issue to something more like:

- Go to _some_ webpage
- Select some text and copy to the clipboard
- Open the markdown editor and press paste
- _Sometimes something_ is inserted into the editor

Some of the questions I have are:
- What category of HTML is expected to work?
- Should we have a list of "priority Web sites" from which we expect cut/paste to work? (e.g., our own docs.accordproject.org? wikipedia? BBC? others?)
- What should be the behaviour when it is _not_ working? Do we have a way to notify users that some information has been lost? formatting might be lost?

**Comment by irmerk** [comment]
I believe this relates to #344

**Comment by irmerk** [comment]
Seems resolved. Open new in `web-components` if not.
