### ISSUE TITLE
New Line Support

### ISSUE THREAD

**Issue by irmerk** [accordproject/markdown-editor#54]
## Current Behavior
- [Commonmark.js](https://github.com/commonmark/commonmark.js/) parser enters a `</html>` tag inside a block when a linbreak is added. The end of the block (`</clause>`) is then treated as a standalone `<html></html>` block.

![commonmark](https://user-images.githubusercontent.com/36460856/59723345-596eeb80-91f4-11e9-84ad-34c2b89de8df.png)

## Tasks
- Ensure every code block (example: `<clause></clause>`) is treated as existing inside the overall html block once.

## Related Issues: 
- N/A

**Comment by dselman** [comment]
This is due to how CommonMark handles html blocks (there are 7 types!):
https://github.com/commonmark/commonmark-spec/blob/master/spec.txt#L2019

I have identified 3 options that preserve the newlines inside the nested custom blocks:
1 pre
2 code blocks
3 blockquotes

(1) and (2) are similar in that the markdown is not parsed by CommonMark, while (3) allows the markdown to be parsed in a single pass.

Example:

```
## Try CommonMark

Using a `pre`

<pre clause="123">
## Heading One
This is text 

and may include newlines. It will not be parsed as markdown, so
we will have to parse a second time.
</pre>

Using a code block

``` clause id="123"
## Heading One
This is text 

and may include newlines. It will not be parsed as markdown, so
we will have to parse a second time.
```

Using a block quote, we will see the markdown...

> clause id="123"
> 
> ## Clause 1.1
> 
> **three**
> ***four***
> ### Sub Section 1.1.1
> This is some text.
>
> This is more text.
> 

This is outside the clause.
```

**Comment by dselman** [comment]
Resolved by: https://github.com/accordproject/markdown-editor/commit/90854c6491d9b908bc28bbbba783550a0105efc5#diff-25d902c24283ab8cfbac54dfa101ad31
